const mongoose = require('mongoose');

/**
 * Alert Model
 *
 * Stores alerts generated by the system when certain conditions are met:
 * - Temperature exceeds threshold (TEMPERATURE_SPIKE event)
 * - Shipment stationary for too long
 * - Customs clearance delays
 *
 * Generated by: alertService.js (Day 11)
 * Queried by: GET /api/queries/alerts, GET /api/queries/shipment/:id/alerts
 */
const alertSchema = new mongoose.Schema(
  {
    shipmentId: {
      type: String,
      required: true,
      index: true,
    },
    type: {
      type: String,
      enum: ['TEMPERATURE_SPIKE', 'STATIONARY_WARNING', 'CUSTOMS_DELAY', 'DELIVERY_OVERDUE'],
      required: true,
      index: true,
    },
    message: {
      type: String,
      required: true,
    },
    severity: {
      type: String,
      enum: ['critical', 'warning', 'info'],
      required: true,
      index: true,
    },
    timestamp: {
      type: Date,
      default: Date.now,
      index: true,
    },
    acknowledged: {
      type: Boolean,
      default: false,
    },
    acknowledgedAt: {
      type: Date,
      default: null,
    },
    metadata: {
      temperature: Number,
      threshold: Number,
      location: String,
      eventVersion: Number,
    },
  },
  {
    timestamps: true,
    collection: 'alerts',
  }
);

// Compound index for filtered queries (severity + timestamp descending)
alertSchema.index({ severity: 1, timestamp: -1 });

// Compound index for shipment-specific alert queries
alertSchema.index({ shipmentId: 1, timestamp: -1 });

const Alert = mongoose.model('Alert', alertSchema);

module.exports = Alert;
